In [ ]:
'''
Group by
Aggregate Functions -> (mean, max, min, count, sum)
Order by -> sort_values(ascending=True/False, by=column_name, ignore_index=True/False (default))
rename -> dictionary {'current_column_name':'replaced_column_name'}
agg -> for analysis of multiple aggregate function columns
'''

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('hr_cleaned_data.csv')

In [ ]:
df.head()

In [ ]:
df.columns

In [ ]:
# Find total employees hired through each Recruitment Source.
'''
    Syntax
    -------
    -> dataframe.groupby(column_name)[column_name].agg_function()
'''
# df['RecruitmentSource'].unique()

In [ ]:
emp_recruitement = df.groupby('RecruitmentSource')['EmpID'].count()

In [ ]:
emp_recruitement

In [ ]:
emp_recruitement = df.groupby('RecruitmentSource')['EmpID'].count().reset_index().rename(
    columns = {'EmpID': 'Total Employees', 'RecruitmentSource': 'Recruitment Source'}
).sort_values(ascending=False, by='Total Employees', ignore_index=True)
emp_recruitement.tail()

In [ ]:
emp_recruitement = df.groupby('RecruitmentSource')['EmpID'].count().rename('Total Employees').rename_axis('Recruitment Source')
format_data = emp_recruitement.to_markdown(numalign='center', stralign='center')

In [ ]:
print(format_data)

In [ ]:
# Find total employees hired through each Recruitment Source and Gender.
recruitment_gender = df.groupby(['RecruitmentSource', 'Gender'])['EmpID'].count().reset_index().rename(
    columns = {'RecruitmentSource': 'Recruitment Source', 'EmpID':'Total Employees'}
)
recruitment_gender

In [ ]:
def changeCurrency(dataframe, prefix, *args):
    for col in args:
        dataframe[col] = dataframe[col].map(f'{prefix}''{:,.2f}'.format)

In [ ]:
# Find total employees hired and total salary distribution of employees by each Recruitment Source and Gender.
rec_gen_sal = df.groupby(['RecruitmentSource', 'Gender']).agg(
    Total_Employees = ('EmpID', 'count'),
    Total_Salary = ('Salary', 'sum'),
    Max_Salary = ('Salary', 'max'),
    Min_Salary = ('Salary', 'min')
).reset_index()
# rec_gen_sal['Total_Salary'] = rec_gen_sal['Total_Salary'].map('${:,.2f}'.format)
changeCurrency(rec_gen_sal, 'Rs.', 'Total_Salary', 'Max_Salary', 'Min_Salary')
rec_gen_sal

In [ ]:
rec_gen_sal.info()

In [ ]:
# Extract a metric profile for each performance rating tier. For each tier, find the 
# typical number of absences, the standard survey score for employee commitment, and the 
# worst-case scenario for short-term tardiness (DaysLateLast30).
emp_performance = df.groupby('PerformanceScore').agg(
    Typical_Absences = ('Absences', 'mean'),
    Emp_Survey = ('EngagementSurvey', 'mean'),
    Total_Late_Days = ('DaysLateLast30', 'sum')
).reset_index()
emp_performance

In [ ]:
df.columns

In [ ]:
## Find total number of employees hired in each year.
emp_hired = df.groupby('HireYear')['EmpID'].count().reset_index().rename(
    columns = {'EmpID': 'Total Employees'}
)
# pct_change()
emp_hired['Hire%'] = round(emp_hired['Total Employees'].pct_change().fillna(0), 2)*100
emp_hired['Hire%'] = emp_hired['Hire%'].map('{:,.2f}%'.format)
emp_hired

# DateTime -> YTD (Year to Date), MTD (Month to Date), DTD (Day to Date)

#### Month wise total hire employees

In [ ]:
# select HireMonth_Name, EmpID as Total Employees from employees
# group by 'HireMonth', 'HireMonth_Name';

In [ ]:
emp_month_hire = df.groupby(['HireMonth', 'HireMonth_Name'])['EmpID'].count().reset_index().rename(
    columns = {'EmpID': 'Total Employees'}
)[['HireMonth_Name', 'Total Employees']]
emp_month_hire

#### Day wise total employees hire

In [ ]:
# Pandas Category -> pd.Categorical(column_name, categories)
days = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']
df['HireDay_Name'] = pd.Categorical(df['HireDay_Name'], categories=days)
df['HireDay_Name'].unique()

In [ ]:
emp_day_hire = df.groupby('HireDay_Name', observed=False)['EmpID'].count().reset_index().rename(
    columns = {'EmpID': 'Total Employees'}
)
emp_day_hire

In [ ]:
linked_in_df = df[df['RecruitmentSource'] == 'LinkedIn']

In [ ]:
# linked_in_df

### KPIs (Key Performance Indicator)

In [ ]:
total_employees = df['EmpID'].count()
# nunique -> number of unique record
total_departments = df['Department'].nunique()
total_managers = df['ManagerID'].nunique()
total_salary = df['Salary'].sum()

In [ ]:
print(f'Total Employees: {total_employees}')
print(f'Total Departments: {total_departments}')
print(f'Total Managers: {total_managers}')
print(f'Total Salary: Rs.{total_salary:,.2f}')

In [ ]:
# SQL
# -----
# Basic Select
# SQL CASE
# Group by and Having
# JOINS
#     1. Inner Join
#     2. Left Join
#     3. Right Join
#     4. Outer Join
#     5. Self Join
#     6. Natural Join
#     7. Cross Join
# SubQueries
# CTEs (Common Table Expressions)
# Window Functions
#     1. Row_Number
#     2. Rank
#     3. Dense_Rank
#     4. NTile
#     5. Lead
#     6. Lag
#     7. Running Sum (Cumilative Sum)
#     8. Running Avg (Cumilative Average)
# Views
# Indexing
# Synonyms
# Basic Stored Procedure

In [ ]:
#!pip install sqlalchemy pyodbc

In [11]:
import pandas as pd
from sqlalchemy import create_engine

In [12]:
server='DESKTOP-69J7G7I'
database='BikeStores'
connection_url = f"mssql+pyodbc://@{server}/{database}?driver=ODBC+Driver+17+for+SQL+Server&trusted_connection=yes"
engine = create_engine(connection_url)

In [13]:
query1=''' select * from sales.customers
'''
data=pd.read_sql(query1, engine)

In [14]:
data.head()

,customer_id,first_name,last_name,phone,email,street,city,state,zip_code
0,1,Debra,Burks,NaN,debra.burks@yahoo.com,9273 Thorne Ave.,Orchard Park,NY,14127
1,2,Kasha,Todd,NaN,kasha.todd@yahoo.com,910 Vine Street,Campbell,CA,95008
2,3,Tameka,Fisher,NaN,tameka.fisher@aol.com,769C Honey Creek St.,Redondo Beach,CA,90278
3,4,Daryl,Spence,NaN,daryl.spence@aol.com,988 Pearl Lane,Uniondale,NY,11553
4,5,Charolette,Rice,(916) 381-6003,charolette.rice@msn.com,107 River Dr.,Sacramento,CA,95820

In [ ]:
#If there is user_name and password
#conn_str = f"DRIVER={{ODBC Driver 17 for SQL Server}};SERVER={server};DATABASE={database};UID=your_username;PWD=your_password;"

In [15]:
query_sp='''
exec customer_orders 'NY'
'''
query_sp_df=pd.read_sql(query_sp,engine)
query_sp_df

,customer_id,first_name,last_name,phone,email,street,city,state,zip_code
0,1,Debra,Burks,NaN,debra.burks@yahoo.com,9273 Thorne Ave.,Orchard Park,NY,14127
1,4,Daryl,Spence,NaN,daryl.spence@aol.com,988 Pearl Lane,Uniondale,NY,11553
2,6,Lyndsey,Bean,NaN,lyndsey.bean@hotmail.com,769 West Road,Fairport,NY,14450
3,7,Latasha,Hays,(716) 986-3359,latasha.hays@hotmail.com,7014 Manor Station Rd.,Buffalo,NY,14215
4,8,Jacquline,Duncan,NaN,jacquline.duncan@yahoo.com,15 Brown St.,Jackson Heights,NY,11372
...,...,...,...,...,...,...,...,...,...
1014,1440,Ernest,Rollins,NaN,ernest.rollins@yahoo.com,4 West Ridge Dr.,Oakland Gardens,NY,11364
1015,1441,Jamaal,Morrison,NaN,jamaal.morrison@msn.com,796 SE. Nut Swamp St.,Staten Island,NY,10301
1016,1442,Cassie,Cline,NaN,cassie.cline@gmail.com,947 Lafayette Drive,Brooklyn,NY,11201
1017,1443,Lezlie,Lamb,NaN,lezlie.lamb@gmail.com,401 Brandywine Street,Central Islip,NY,11722
1018,1444,Ivette,Estes,NaN,ivette.estes@gmail.com,88 N. Canterbury Ave.,Canandaigua,NY,14424