In [1]:
'''
Group by
Aggregate Functions -> (mean, max, min, count, sum)
Order by -> sort_values(ascending=True/False, by=column_name, ignore_index=True/False (default))
rename -> dictionary {'current_column_name':'replaced_column_name'}
agg -> for analysis of multiple aggregate function columns
'''

"\nGroup by\nAggregate Functions -> (mean, max, min, count, sum)\nOrder by -> sort_values(ascending=True/False, by=column_name, ignore_index=True/False (default))\nrename -> dictionary {'current_column_name':'replaced_column_name'}\nagg -> for analysis of multiple aggregate function columns\n"

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('hr_cleaned_data.csv')

In [4]:
df.head()

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,Salary_Label,salary_label_num,PerformanceScore_id,HireDay_Name_id,E_FirstName,E_MiddleName,E_LastName,M_first_name,M_middle_name,M_last_name
0,Adinolfi Wilson K,10026,0,0,1,1,5,4,0,62506,...,Low Salary,0,0,0,Wilson,K,Adinolfi,Michael,NaN,Albert
1,Ait Sidi Karthikeyan,10084,1,1,1,5,3,3,0,104437,...,Medium Salary,1,1,1,Karthikeyan,NaN,Ait Sidi,Simon,NaN,Roup
2,Akinkuolie Sarah,10196,1,1,0,5,5,3,0,64955,...,Low Salary,0,1,0,Sarah,NaN,Akinkuolie,Kissy,NaN,Sullivan
3,Alagbe Trina,10088,1,1,0,1,5,3,0,64991,...,Low Salary,0,1,1,Trina,NaN,Alagbe,Elijiah,NaN,Gray
4,Anderson Carol,10069,0,2,0,5,5,3,0,50825,...,Low Salary,0,1,1,Carol,NaN,Anderson,Webster,NaN,Butler

In [5]:
df.columns

Index(['Employee_Name', 'EmpID', 'MarriedID', 'MaritalStatusID', 'GenderID',
       'EmpStatusID', 'DeptID', 'PerfScoreID', 'FromDiversityJobFairID',
       'Salary', 'Termd', 'PositionID', 'Position', 'State', 'Zip', 'DOB',
       'Gender', 'MaritalDesc', 'CitizenDesc', 'HispanicLatino', 'RaceDesc',
       'DateofHire', 'DateofTermination', 'TermReason', 'EmploymentStatus',
       'Department', 'ManagerName', 'ManagerID', 'RecruitmentSource',
       'PerformanceScore', 'EngagementSurvey', 'EmpSatisfaction',
       'SpecialProjectsCount', 'LastPerformanceReview_Date', 'DaysLateLast30',
       'Absences', 'HireYear', 'HireMonth', 'HireDay', 'HireMonth_Name',
       'HireDay_Name', 'Salary_Label', 'salary_label_num',
       'PerformanceScore_id', 'HireDay_Name_id', 'E_FirstName', 'E_MiddleName',
       'E_LastName', 'M_first_name', 'M_middle_name', 'M_last_name'],
      dtype='str')

In [6]:
# Find total employees hired through each Recruitment Source.
'''
    Syntax
    -------
    -> dataframe.groupby(column_name)[column_name].agg_function()
'''
# df['RecruitmentSource'].unique()

'\n    Syntax\n    -------\n    -> dataframe.groupby(column_name)[column_name].agg_function()\n'

In [7]:
emp_recruitement = df.groupby('RecruitmentSource')['EmpID'].count()

In [8]:
emp_recruitement

RecruitmentSource
CareerBuilder               23
Diversity Job Fair          61
Employee Referral           61
Google Search               82
Indeed                     146
LinkedIn                   192
On-line Web application      2
Other                        2
Website                     13
Name: EmpID, dtype: int64

In [9]:
emp_recruitement = df.groupby('RecruitmentSource')['EmpID'].count().reset_index().rename(
    columns = {'EmpID': 'Total Employees', 'RecruitmentSource': 'Recruitment Source'}
).sort_values(ascending=False, by='Total Employees', ignore_index=True)
emp_recruitement.tail()

        Recruitment Source  Total Employees
4        Employee Referral               61
5            CareerBuilder               23
6                  Website               13
7  On-line Web application                2
8                    Other                2

In [10]:
emp_recruitement = df.groupby('RecruitmentSource')['EmpID'].count().rename('Total Employees').rename_axis('Recruitment Source')
format_data = emp_recruitement.to_markdown(numalign='center', stralign='center')

ImportError: `Import tabulate` failed.  Use pip or conda to install the tabulate package.

In [ ]:
print(format_data)

|   Recruitment Source    |  Total Employees  |
|:-----------------------:|:-----------------:|
|      CareerBuilder      |        23         |
|   Diversity Job Fair    |        61         |
|    Employee Referral    |        61         |
|      Google Search      |        82         |
|         Indeed          |        146        |
|        LinkedIn         |        192        |
| On-line Web application |         2         |
|          Other          |         2         |
|         Website         |        13         |

In [ ]:
# Find total employees hired through each Recruitment Source and Gender.
recruitment_gender = df.groupby(['RecruitmentSource', 'Gender'])['EmpID'].count().reset_index().rename(
    columns = {'RecruitmentSource': 'Recruitment Source', 'EmpID':'Total Employees'}
)
recruitment_gender

         Recruitment Source Gender  Total Employees
0             CareerBuilder      F               16
1             CareerBuilder      M                7
2        Diversity Job Fair      F               45
3        Diversity Job Fair      M               16
4         Employee Referral      F               12
5         Employee Referral      M               49
6             Google Search      F               64
7             Google Search      M               18
8                    Indeed      F               79
9                    Indeed      M               67
10                 LinkedIn      F              131
11                 LinkedIn      M               61
12  On-line Web application      M                2
13                    Other      F                1
14                    Other      M                1
15                  Website      F                6
16                  Website      M                7

In [ ]:
def changeCurrency(dataframe, prefix, *args):
    for col in args:
        dataframe[col] = dataframe[col].map(f'{prefix}''{:,.2f}'.format)

In [ ]:
# Find total employees hired and total salary distribution of employees by each Recruitment Source and Gender.
rec_gen_sal = df.groupby(['RecruitmentSource', 'Gender']).agg(
    Total_Employees = ('EmpID', 'count'),
    Total_Salary = ('Salary', 'sum'),
    Max_Salary = ('Salary', 'max'),
    Min_Salary = ('Salary', 'min')
).reset_index()
# rec_gen_sal['Total_Salary'] = rec_gen_sal['Total_Salary'].map('${:,.2f}'.format)
changeCurrency(rec_gen_sal, 'Rs.', 'Total_Salary', 'Max_Salary', 'Min_Salary')
rec_gen_sal

,RecruitmentSource,Gender,Total_Employees,Total_Salary,Max_Salary,Min_Salary
0,CareerBuilder,F,16,"Rs.989,848.00","Rs.101,199.00","Rs.46,335.00"
1,CareerBuilder,M,7,"Rs.470,250.00","Rs.93,046.00","Rs.46,837.00"
2,Diversity Job Fair,F,45,"Rs.3,202,621.00","Rs.650,000.00","Rs.47,434.00"
3,Diversity Job Fair,M,16,"Rs.1,328,473.00","Rs.157,000.00","Rs.47,211.00"
4,Employee Referral,F,12,"Rs.1,040,301.00","Rs.220,450.00","Rs.45,069.00"
5,Employee Referral,M,49,"Rs.4,046,433.00","Rs.500,000.00","Rs.46,664.00"
6,Google Search,F,64,"Rs.4,124,312.00","Rs.500,825.00","Rs.45,433.00"
7,Google Search,M,18,"Rs.1,061,679.00","Rs.77,692.00","Rs.46,428.00"
8,Indeed,F,79,"Rs.5,511,116.00","Rs.250,000.00","Rs.46,430.00"
9,Indeed,M,67,"Rs.6,020,604.00","Rs.178,000.00","Rs.50,178.00"
10,LinkedIn,F,131,"Rs.9,825,058.00","Rs.650,000.00","Rs.45,046.00"
11,LinkedIn,M,61,"Rs.3,801,915.00","Rs.103,613.00","Rs.45,115.00"
12,On-line Web application,M,2,"Rs.105,010.00","Rs.52,505.00","Rs.52,505.00"
13,Other,F,1,"Rs.99,351.00","Rs.99,351.00","Rs.99,351.00"
14,Other,M,1,"Rs.67,176.00","Rs.67,176.00","Rs.67,176.00"
15,Website,F,6,"Rs.363,594.00","Rs.77,915.00","Rs.51,920.00"
16,Website,M,7,"Rs.436,396.00","Rs.70,468.00","Rs.55,140.00"

In [ ]:
rec_gen_sal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17 entries, 0 to 16
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   RecruitmentSource  17 non-null     object
 1   Gender             17 non-null     object
 2   Total_Employees    17 non-null     int64
 3   Total_Salary       17 non-null     object
 4   Max_Salary         17 non-null     object
 5   Min_Salary         17 non-null     object
dtypes: int64(1), object(5)
memory usage: 948.0+ bytes

In [ ]:
# Extract a metric profile for each performance rating tier. For each tier, find the 
# typical number of absences, the standard survey score for employee commitment, and the 
# worst-case scenario for short-term tardiness (DaysLateLast30).
emp_performance = df.groupby('PerformanceScore').agg(
    Typical_Absences = ('Absences', 'mean'),
    Emp_Survey = ('EngagementSurvey', 'mean'),
    Total_Late_Days = ('DaysLateLast30', 'sum')
).reset_index()
emp_performance

    PerformanceScore  Typical_Absences  Emp_Survey  Total_Late_Days
0            Exceeds          9.041237    4.667938                0
1        Fully Meets         10.718062    4.287643                5
2  Needs Improvement         11.333333    2.991111               68
3                PIP          8.307692    2.219231               56

In [ ]:
df.columns

Index(['Employee_Name', 'EmpID', 'MarriedID', 'MaritalStatusID', 'GenderID',
       'EmpStatusID', 'DeptID', 'PerfScoreID', 'FromDiversityJobFairID',
       'Salary', 'Termd', 'PositionID', 'Position', 'State', 'Zip', 'DOB',
       'Gender', 'MaritalDesc', 'CitizenDesc', 'HispanicLatino', 'RaceDesc',
       'DateofHire', 'DateofTermination', 'TermReason', 'EmploymentStatus',
       'Department', 'ManagerName', 'ManagerID', 'RecruitmentSource',
       'PerformanceScore', 'EngagementSurvey', 'EmpSatisfaction',
       'SpecialProjectsCount', 'LastPerformanceReview_Date', 'DaysLateLast30',
       'Absences', 'HireYear', 'HireMonth', 'HireDay', 'HireMonth_Name',
       'HireDay_Name', 'Salary_Label', 'salary_label_num',
       'PerformanceScore_id', 'HireDay_Name_id', 'E_FirstName', 'E_MiddleName',
       'E_LastName', 'M_first_name', 'M_middle_name', 'M_last_name'],
      dtype='object')

In [ ]:
## Find total number of employees hired in each year.
emp_hired = df.groupby('HireYear')['EmpID'].count().reset_index().rename(
    columns = {'EmpID': 'Total Employees'}
)
# pct_change()
emp_hired['Hire%'] = round(emp_hired['Total Employees'].pct_change().fillna(0), 2)*100
emp_hired['Hire%'] = emp_hired['Hire%'].map('{:,.2f}%'.format)
emp_hired

# DateTime -> YTD (Year to Date), MTD (Month to Date), DTD (Day to Date)

    HireYear  Total Employees      Hire%
0       2006                1      0.00%
1       2007                2    100.00%
2       2008               32  1,500.00%
3       2009               36     12.00%
4       2010                9    -75.00%
5       2011              173  1,822.00%
6       2012               77    -55.00%
7       2013               73     -5.00%
8       2014               91     25.00%
9       2015               66    -27.00%
10      2016               15    -77.00%
11      2017                6    -60.00%
12      2018                1    -83.00%

#### Month wise total hire employees

In [ ]:
# select HireMonth_Name, EmpID as Total Employees from employees
# group by 'HireMonth', 'HireMonth_Name';

In [ ]:
emp_month_hire = df.groupby(['HireMonth', 'HireMonth_Name'])['EmpID'].count().reset_index().rename(
    columns = {'EmpID': 'Total Employees'}
)[['HireMonth_Name', 'Total Employees']]
emp_month_hire

   HireMonth_Name  Total Employees
0         January              114
1        February               33
2           March               48
3           April               29
4             May               33
5            June                8
6            July              162
7          August               20
8       September               69
9         October                7
10       November               58
11       December                1

#### Day wise total employees hire

In [ ]:
# Pandas Category -> pd.Categorical(column_name, categories)
days = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']
df['HireDay_Name'] = pd.Categorical(df['HireDay_Name'], categories=days)
df['HireDay_Name'].unique()

['Tuesday', 'Monday', 'Thursday', 'Wednesday', 'Sunday', 'Friday', 'Saturday']
Categories (7, object): ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']

In [ ]:
emp_day_hire = df.groupby('HireDay_Name', observed=False)['EmpID'].count().reset_index().rename(
    columns = {'EmpID': 'Total Employees'}
)
emp_day_hire

  HireDay_Name  Total Employees
0       Sunday                6
1       Monday              471
2      Tuesday               77
3    Wednesday                9
4     Thursday               10
5       Friday                6
6     Saturday                3

In [ ]:
linked_in_df = df[df['RecruitmentSource'] == 'LinkedIn']

In [ ]:
# linked_in_df

### KPIs (Key Performance Indicator)

In [ ]:
total_employees = df['EmpID'].count()
# nunique -> number of unique record
total_departments = df['Department'].nunique()
total_managers = df['ManagerID'].nunique()
total_salary = df['Salary'].sum()

In [ ]:
print(f'Total Employees: {total_employees}')
print(f'Total Departments: {total_departments}')
print(f'Total Managers: {total_managers}')
print(f'Total Salary: Rs.{total_salary:,.2f}')

Total Employees: 582
Total Departments: 6
Total Managers: 23
Total Salary: Rs.42,494,137.00

In [ ]:
# SQL
# -----
# Basic Select
# SQL CASE
# Group by and Having
# JOINS
#     1. Inner Join
#     2. Left Join
#     3. Right Join
#     4. Outer Join
#     5. Self Join
#     6. Natural Join
#     7. Cross Join
# SubQueries
# CTEs (Common Table Expressions)
# Window Functions
#     1. Row_Number
#     2. Rank
#     3. Dense_Rank
#     4. NTile
#     5. Lead
#     6. Lag
#     7. Running Sum (Cumilative Sum)
#     8. Running Avg (Cumilative Average)
# Views
# Indexing
# Synonyms
# Basic Stored Procedure

In [ ]:
#!pip install sqlalchemy pyodbc

In [11]:
import pandas
from sqlalchemy import create_engine

In [12]:
server='DESKTOP-69J7G7I'
database='BikeStores'
connection_url = f"mssql+pyodbc://@{server}/{database}?driver=ODBC+Driver+17+for+SQL+Server&trusted_connection=yes"
engine = create_engine(connection_url)

In [13]:
query1=''' select * from sales.customers
'''
data=pd.read_sql(query1, engine)

In [ ]:
data.head()

,customer_id,first_name,last_name,phone,email,street,city,state,zip_code
0,1,Debra,Burks,NaN,debra.burks@yahoo.com,9273 Thorne Ave.,Orchard Park,NY,14127
1,2,Kasha,Todd,NaN,kasha.todd@yahoo.com,910 Vine Street,Campbell,CA,95008
2,3,Tameka,Fisher,NaN,tameka.fisher@aol.com,769C Honey Creek St.,Redondo Beach,CA,90278
3,4,Daryl,Spence,NaN,daryl.spence@aol.com,988 Pearl Lane,Uniondale,NY,11553
4,5,Charolette,Rice,(916) 381-6003,charolette.rice@msn.com,107 River Dr.,Sacramento,CA,95820

In [ ]:
#If there is user_name and password
#conn_str = f"DRIVER={{ODBC Driver 17 for SQL Server}};SERVER={server};DATABASE={database};UID=your_username;PWD=your_password;"