Hypothesis Testing

In [1]:
''' 1 Year business
average profit = 50000 -> Sample

Total Sales = 1300000 -> Population

Types of Hypothesis Testing
1. T Test
        a.One Sample T Test
        b.Two Sample T Test

2.ANOVA Test 
3.Chi Square Test


--Statistics 
--Probability

stats->(Actual Mean - Sample Mean)/(sd/root(total_number))

-If Stats value increases P-Value decrease
-If Stats value decreases P-Value increases

'''

' 1 Year business\naverage profit = 50000 -> Sample\n\nTotal Sales = 1300000 -> Population\n\nTypes of Hypothesis Testing\n1. T Test\n        a.One Sample T Test\n        b.Two Sample T Test\n\n2.ANOVA Test \n3.Chi Square Test\n\n\n--Statistics \n--Probability\n\nstats->(Actual Mean - Sample Mean)/(sd/root(total_number))\n\n-If Stats value increases P-Value decrease\n-If Stats value decreases P-Value increases\n\n'

In [2]:
#Statistical calculation -> scipy -> scientific python
from scipy import stats
import pandas as pd

In [3]:
df=pd.read_csv('Dataset/pizza_sales.csv')
df.head()

,pizza_id,order_id,pizza_name_id,quantity,order_date,order_time,unit_price,total_price,pizza_size,pizza_category,pizza_ingredients,pizza_name
0,1,1,hawaiian_m,1,1/1/2015,11:38:36,13.25,13.25,M,Classic,"Sliced Ham, Pineapple, Mozzarella Cheese",The Hawaiian Pizza
1,2,2,classic_dlx_m,1,1/1/2015,11:57:40,16.00,16.00,M,Classic,"Pepperoni, Mushrooms, Red Onions, Red Peppers,...",The Classic Deluxe Pizza
2,3,2,five_cheese_l,1,1/1/2015,11:57:40,18.50,18.50,L,Veggie,"Mozzarella Cheese, Provolone Cheese, Smoked Go...",The Five Cheese Pizza
3,4,2,ital_supr_l,1,1/1/2015,11:57:40,20.75,20.75,L,Supreme,"Calabrese Salami, Capocollo, Tomatoes, Red Oni...",The Italian Supreme Pizza
4,5,2,mexicana_m,1,1/1/2015,11:57:40,16.00,16.00,M,Veggie,"Tomatoes, Red Peppers, Jalapeno Peppers, Red O...",The Mexicana Pizza

One Sample T test

is the average total price of all pizza sales different from $15?

In [4]:
'''
import numpy as np
actual_mean = population.mean()
sd=population.std()
total_data = np.sqrt(48619)

top_val = actual_mean - sample
bot_val = sd / total_data

top_val / bot_val

'''

'\nimport numpy as np\nactual_mean = population.mean()\nsd=population.std()\ntotal_data = np.sqrt(48619)\n\ntop_val = actual_mean - sample\nbot_val = sd / total_data\n\ntop_val / bot_val\n\n'

In [5]:
alpha=0.05
sample = 15
population = df['total_price']

In [6]:
# stats.ttest_1samp(population,popmean=sample)
statistics,p_value=stats.ttest_1samp(population,popmean=sample)

In [7]:
ho = f'The average total price of all pizza sales equals to ${sample}'
ha = f'The average total price of all pizza sales is not equal to ${sample}'

In [8]:
def decision_function(ha,ho):
    if p_value < alpha :
        print(f'Decision: Failed to accept null hypothesis.\nConclusion: Needs to accept alternate hypothesis.\n Ha: {ha}')
    else:
       print(f'Decision: Failed to reject null hypothesis.\nConclusion: Needs to accept Null hypothesis.\n Ho: {ho}')

In [9]:
decision_function(ha,ho)

Decision: Failed to accept null hypothesis.
Conclusion: Needs to accept alternate hypothesis.
 Ha: The average total price of all pizza sales is not equal to $15

Two Sample T Test

The average unit price of Classic Pizzas and Chicken Pizzas Same?

In [10]:
alpha = 0.5
classic_price = df[df['pizza_category'] == 'Classic']['unit_price']
chicken_price = df[df['pizza_category']=='Chicken']['unit_price']

In [11]:
#stats.ttest_ind(category1, category2 , equal_var=True/False)
t_statistics,p_value =stats.ttest_ind(classic_price,chicken_price,equal_var=False)

In [12]:
ho = 'The Average unit price of Classic Pizzas and Chicken Pizzas are equal.'
ha= 'The average unit price of Classic and Chicken Pizzas are not Equal'

In [13]:
decision_function(ho=ho,ha=ha)

Decision: Failed to accept null hypothesis.
Conclusion: Needs to accept alternate hypothesis.
 Ha: The average unit price of Classic and Chicken Pizzas are not Equal

ANOVA Test (Analysis Of Variance)

Do the average total_price generated by all four pizza categories
(Classic, Chicken, Supreme, and Veggie) differ significantly from one another?​

In [14]:
alpha = 0.5
categories = ['Classic', 'Chicken', 'Supreme', 'Veggie' ]
grouped_prices = []

for category in categories:
   price=df[df['pizza_category']==category]['total_price']
   grouped_prices.append(price)

In [15]:
t_statistics, p_value = stats.f_oneway(*grouped_prices)

In [16]:
#pizza_price=df.groupby(['pizza_category'])['total_price'].mean().rename_axis('Pizza Category').rename('Total Price').map("${:,.2f}".format).to_markdown(numalign='center',stralign='center')

In [17]:
ho='The average price generated by all four pizza categories are equal to one another.'
ha='The average  total price generated by all four pizza categories are not equal to one another.'

print(f'Ho: {ho}')
print(f'Ha: {ha}')

Ho: The average price generated by all four pizza categories are equal to one another.
Ha: The average  total price generated by all four pizza categories are not equal to one another.

In [18]:
decision_function(ho=ho,ha=ha)

Decision: Failed to accept null hypothesis.
Conclusion: Needs to accept alternate hypothesis.
 Ha: The average  total price generated by all four pizza categories are not equal to one another.

### Chi-Squared Test

IS pizza Category and Pizza Size are dependent to one another

In [21]:
alpha=0.5
# contingency analysis -> crosstab(Cross Tabulation)
contingency =  pd.crosstab(df['pizza_category'],df['pizza_size'])
contingency

pizza_size         L     M     S   XL  XXL
pizza_category
Chicken         4799  3811  2205    0    0
Classic         3987  4045  5975  544   28
Supreme         4477  3977  3323    0    0
Veggie          5263  3552  2634    0    0

In [ ]:
#dof = (numbers of rows - 1 ) * (number of columns - 1)

In [ ]:
statistics,p_value,dof,ef=stats.chi2_contingency(contingency)

array([[4120.910942  , 3422.22902098, 3144.6247429 ,  121.00699301,
           6.22830111],
       [5555.13274373, 4613.28496503, 4239.06464418,  163.12167832,
           8.39596874],
       [4487.46816125, 3726.63811189, 3424.34078568,  131.77062937,
           6.78231181],
       [4362.48815302, 3622.8479021 , 3328.96982723,  128.1006993 ,
           6.59341835]])

In [23]:
ho = 'Pizza Category and pizza size are dependent to one other.'
ha = 'Pizza Category and pizza size are independent to one other.'

decision_function(ho=ho,ha=ha)

Decision: Failed to accept null hypothesis.
Conclusion: Needs to accept alternate hypothesis.
 Ha: Pizza Category and pizza size are independent to one other.